### ISSUE TITLE
libpointmatcher

### ISSUE THREAD

**Issue by Russ76** [MobileRobotics-Ulaval/husky-trainer#3]
Is it necessary to install libpointmatcher from its repository? When I try to compile Husky-trainer Cmake is requesting some files regarding this other program before it will finish without error.

-- Could not find the required component 'libpointmatcher'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "libpointmatcher"
  with any of the following names:

    libpointmatcherConfig.cmake
    libpointmatcher-config.cmake

  Add the installation prefix of "libpointmatcher" to CMAKE_PREFIX_PATH or
  set "libpointmatcher_DIR" to a directory containing one of the above files.
  If "libpointmatcher" provides a separate development package or SDK, be
  sure it has been installed.

**Comment by Russ76** [comment]
Before the above, the error was:

-- Could not find the required component 'pointmatcher_ros'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "pointmatcher_ros"
  with any of the following names:

    pointmatcher_rosConfig.cmake
    pointmatcher_ros-config.cmake

  Add the installation prefix of "pointmatcher_ros" to CMAKE_PREFIX_PATH or
  set "pointmatcher_ros_DIR" to a directory containing one of the above
  files.  If "pointmatcher_ros" provides a separate development package or
  SDK, be sure it has been installed.

So I grabbed that program and installed it. That was easy enough. But libpointmatcher is not a catkin module.

**Comment by davidlandry93** [comment]
Yes libpointmatcher has to be installed beforehand. You can get it [here](https://github.com/ethz-asl/libpointmatcher). Usually the standard cmake procedure does the trick. If you are not familiar with it there are instructions on libpointmatcher's repo. Note that libpointmatcher itself has a dependency ;) So you have at least two cmake packages to install still.

About pointmatcher_ros, you may run into an issue with it. When my own code was running on hydro, I needed to modify pointmatcher_ros. That modified version is available [here](https://github.com/MobileRobotics-Ulaval/pointmatcher-ros). 

Now that husky-trainer is on indigo, i'm not sure the fork is necessary anymore. I suggest you try it with the default package first. If you run into timeout issues, try the patched version.

**Comment by Russ76** [comment]
Thanks, David. I will try that. I'm using Indigo, also.

**Comment by matteopantano** [comment]
I have tried as you said, but seems that pointmatcher_ros does not work. I am trying to build it but I get that:

`matteo@matteo-S551LB:~/Libraries/pointmatcher-ros/pointmatcher_ros/build$ make
[  0%] Built target _pointmatcher_ros_generate_messages_check_deps_MatchClouds
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target pointmatcher_ros_generate_messages_cpp
[  0%] Built target pointmatcher_ros_gencpp
[  0%] Building CXX object CMakeFiles/matcher_service.dir/src/matcher_service.cpp.o
In file included from /home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:11:0:
/home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h: In member function ‘void PointMatcherSupport::ROSLogger::writeRosLog(ros::console::Level, const char*, int, const char*, const string&)’:
/home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:54:7: error: ‘enabled’ was not declared in this scope
   if (enabled)
       ^
/home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:54:7: note: suggested alternative:
In file included from /usr/include/boost/iterator/iterator_facade.hpp:15:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:23,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /opt/ros/indigo/include/ros/transport_hints.h:34,
                 from /opt/ros/indigo/include/ros/subscribe_options.h:33,
                 from /opt/ros/indigo/include/ros/node_handle.h:41,
                 from /opt/ros/indigo/include/ros/ros.h:45,
                 from /home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:4:
/usr/include/boost/iterator/detail/enable_if.hpp:30:12: note:   ‘boost::iterators::enabled’
     struct enabled
            ^
In file included from /home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:11:0:
/home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:55:27: error: ‘loc’ was not declared in this scope
    ros::console::print(0, loc.logger_, loc.level_, file, line, func, "%s", text.c_str());
                           ^
make[2]: *** [CMakeFiles/matcher_service.dir/src/matcher_service.cpp.o] Error 1
make[1]: *** [CMakeFiles/matcher_service.dir/all] Error 2
make: *** [all] Error 2
`

Hints?

**Comment by matteopantano** [comment]
I have tried. I have installed libpointmatcher with any problem, but pointmatcher_ros is still not working. Here the error when I tire to do `make`:

```
matteo@matteo-S551LB:~/Libraries/pointmatcher-ros/pointmatcher_ros/build$ make
[  0%] Built target _pointmatcher_ros_generate_messages_check_deps_MatchClouds
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target pointmatcher_ros_generate_messages_cpp
[  0%] Built target pointmatcher_ros_gencpp
[  0%] Building CXX object CMakeFiles/matcher_service.dir/src/matcher_service.cpp.o
In file included from /home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:11:0:
/home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h: In member function ‘void PointMatcherSupport::ROSLogger::writeRosLog(ros::console::Level, const char*, int, const char*, const string&)’:
/home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:54:7: error: ‘enabled’ was not declared in this scope
   if (enabled)
       ^
/home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:54:7: note: suggested alternative:
In file included from /usr/include/boost/iterator/iterator_facade.hpp:15:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:23,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /opt/ros/indigo/include/ros/transport_hints.h:34,
                 from /opt/ros/indigo/include/ros/subscribe_options.h:33,
                 from /opt/ros/indigo/include/ros/node_handle.h:41,
                 from /opt/ros/indigo/include/ros/ros.h:45,
                 from /home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:4:
/usr/include/boost/iterator/detail/enable_if.hpp:30:12: note:   ‘boost::iterators::enabled’
     struct enabled
            ^
In file included from /home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:11:0:
/home/matteo/Libraries/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:55:27: error: ‘loc’ was not declared in this scope
    ros::console::print(0, loc.logger_, loc.level_, file, line, func, "%s", text.c_str());
                           ^
make[2]: *** [CMakeFiles/matcher_service.dir/src/matcher_service.cpp.o] Error 1
make[1]: *** [CMakeFiles/matcher_service.dir/all] Error 2
make: *** [all] Error 2
```

Hints?

**Comment by davidlandry93** [comment]
ROS packages are built using a superset of cmake called catkin. You need to use catkin to build this package. Here is a useful tutorial to do so http://wiki.ros.org/catkin/Tutorials/using_a_workspace.

**Comment by matteopantano** [comment]
```
Errors     << pointmatcher_ros:make /home/matteo/rover_ws/logs/pointmatcher_ros/build.make.000.log                                         
In file included from /home/matteo/rover_ws/src/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:11:0:
/home/matteo/rover_ws/src/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h: In member function ‘void PointMatcherSupport::ROSLogger::writeRosLog(ros::console::Level, const char*, int, const char*, const string&)’:
/home/matteo/rover_ws/src/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:54:7: error: ‘enabled’ was not declared in this scope
   if (enabled)
       ^
/home/matteo/rover_ws/src/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:54:7: note: suggested alternative:
In file included from /usr/include/boost/iterator/iterator_facade.hpp:15:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:23,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /opt/ros/indigo/include/ros/transport_hints.h:34,
                 from /opt/ros/indigo/include/ros/subscribe_options.h:33,
                 from /opt/ros/indigo/include/ros/node_handle.h:41,
                 from /opt/ros/indigo/include/ros/ros.h:45,
                 from /home/matteo/rover_ws/src/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:4:
/usr/include/boost/iterator/detail/enable_if.hpp:30:12: note:   ‘boost::iterators::enabled’
     struct enabled
            ^
In file included from /home/matteo/rover_ws/src/pointmatcher-ros/pointmatcher_ros/src/matcher_service.cpp:11:0:
/home/matteo/rover_ws/src/pointmatcher-ros/pointmatcher_ros/include/pointmatcher_ros/ros_logger.h:55:27: error: ‘loc’ was not declared in this scope
    ros::console::print(0, loc.logger_, loc.level_, file, line, func, "%s", text.c_str());
                           ^
make[2]: *** [CMakeFiles/matcher_service.dir/src/matcher_service.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/matcher_service.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
cd /home/matteo/rover_ws/build/pointmatcher_ros; catkin build --get-env pointmatcher_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................
Failed     << pointmatcher_ros:make                       [ Exited with code 2 ]                                                           
Failed    <<< pointmatcher_ros                            [ 31.5 seconds ]        
```
