### ISSUE TITLE
RepeatConfig.h MISSING

### ISSUE THREAD

**Issue by matteopantano** [MobileRobotics-Ulaval/husky-trainer#4]
Hi,
I am trying to use this repository on Indigo, I have had several problems, but now the one with I am facing is that in several programs, like `Controller.cpp` there is a call for include `RepeatConfig.h`. I have searched inside the project but seems not there.

Hints?

**Comment by davidlandry93** [comment]
Hey Matteo,

I just pushed commit  dd7b54d194c9c17219fb2ad620b575aa6ba772f0 which should fix the header generation for DynamicReconfigure. Please try it out!

**Comment by matteopantano** [comment]
Solved, thanks:)
