### ISSUE TITLE
Will this work on ROS Kinetic?

### ISSUE THREAD

**Issue by Russ76** [MobileRobotics-Ulaval/husky-trainer#6]
I was hoping to use this with the ZED stereo camera (and no laser) but I see their latest ROS packages specify Ubuntu 16.04 and ROS Kinetic. It seems ROS Indigo wants Ubuntu 14.04. I am using the NVIDIA Jetson TX1.
Or should I ask this question on the ROS answers page? Thanks!
Here is their link:
https://github.com/stereolabs/zed-ros-wrapper

**Comment by davidlandry93** [comment]
I see no reason why this package would not work on ROS kinetic but it does mean some porting work. You would have to port both husky-trainer and pointmatcher-ros to kinetic. Pull requests are welcome!

As a sidenote, this package was never really intended for use with a stereo camera, so there might be some unexpected results, especially when doing rotations with the robot. If the rotation is too quick and the zed acquisition frequency is too low, you might end up trying to match point clouds that have no overlap.
